# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    -s -w -X github.com/marema31/kamino/cmd.version={{.Version}} -X github.com/marema31/kamino/cmd.commit={{.ShortCommit}} -X github.com/marema31/kamino/cmd.date={{.Date}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: marema31
    name: kamino
brews:
  - github:
      owner: marema31
      name: homebrew-marema31
    description: "Development database content bootstraper"